### ISSUE TITLE
bang error

### ISSUE THREAD

**Issue by 1711500065DelvinReynaldi** [dante4rt/units-network-bot#1]
requestUrl: 'https://rpc-testnet.unit0.dev',
    responseBody: '<html>\r\n' +
      '<head><title>502 Bad Gateway</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>502 Bad Gateway</h1></center>\r\n' +
      '<hr><center>nginx/1.27.0</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n',
    responseStatus: '502 Bad Gateway'
  },
  shortMessage: 'server response 502 Bad Gateway'

**Comment by dante4rt** [comment]
> requestUrl: 'https://rpc-testnet.unit0.dev', responseBody: '\r\n' + '<title>502 Bad Gateway</title>\r\n' + '\r\n' + '
> 
> # 502 Bad Gateway
> \r\n' +
> '
> nginx/1.27.0\r\n' +
> '\r\n' +
> '\r\n',
> responseStatus: '502 Bad Gateway'
> },
> shortMessage: 'server response 502 Bad Gateway'

This error comes from Units Network's side, not from this code.
